spring:
  application:
    name: payment-assignment
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql